#!/usr/bin/env python
# coding: utf-8
import json
import sys
import urllib2
"""
corpid：组别id
corpsecret：组别授权码
<<<授权码如上图所示>>>
touser：成员ID列表，多个接收者用‘|’分隔，toparty填写后可空
toparty：部门ID列表，多个接收者用‘|’分隔，填写后默认发送全组
totag：标签ID列表，多个接收者用‘|’分隔，toparty填写后可空
agentid：企业应用id
msgtype：消息类型，固定为：text
content: 消息内容 (u'xxxxx'格式)
safe：是否是保密消息，0>否，1>是，默认0
"""
class WeChatMSG(object):
    def __init__(self, corpid, corpsecret, partyid, agentid):
        self.gettoken_url = 'https://qyapi.weixin.qq.com/cgi-bin/gettoken'
        self.gettoken_content = {
            'corpid': corpid,
            'corpsecret': corpsecret,
        }
        self.main_content = {
            "touser": "",
            "toparty": partyid,
            "totag": "",
            "agentid": agentid,
            "msgtype": "text",
            "text": {
                "content": "",
            }
        }
    def get_access_token(self, string):
        token_result = json.loads(string.read())
        access_token = token_result['access_token']
        return access_token.encode('utf-8')
    def geturl(self, url, data):
        data = self.encodeurl(data)
        response = urllib2.urlopen('%s?%s' % (url, data))
        return response.read().decode('utf-8')
    def posturl(self, url, data, isjson=True):
        if isjson:
            data = json.dumps(data, ensure_ascii=False).encode('utf-8')
        response = urllib2.urlopen(url, data, timeout=10)
        return response.read().decode('utf-8')
    def encodeurl(self, dict):
        data = ''
        for k, v in dict.items():
            data += '%s=%s%s' % (k, v, '&')
        return data
    def send_weixin(self, content):
        reload(sys)
        sys.setdefaultencoding('utf8')
        self.main_content['text']['content'] = content
        access_token_response = self.geturl(self.gettoken_url, self.gettoken_content)
        access_token = json.loads(access_token_response)['access_token']
        sendmsg_url = 'https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s' % access_token
        response = self.posturl(sendmsg_url, self.main_content)
        code = json.loads(response)['errcode']
        if code == 0:
            return True
        else:
            return False
if __name__ == '__main__':
    id = '**********'
    secret = '**********'
    partyid = "*"
    agentid = "*"
    content = u'时光机器\n' \
              u'应用：时光机器测试\n' \
              u'报警时间：7777-07-07 00:00:00\n' \
              u'报警服务器：未来时间机器\n' \
              u'报警原因：老大哥在看着你 '
    msgsender = WeChatMSG(id, secret, partyid, agentid)
    msgsender.send_weixin(content)
